var annotated_dup =
[
    [ "Account", "class_account.html", "class_account" ],
    [ "AccountManager", "class_account_manager.html", "class_account_manager" ],
    [ "Base_controller", "class_base__controller.html", "class_base__controller" ],
    [ "Category", "class_category.html", "class_category" ],
    [ "CategoryManager", "class_category_manager.html", "class_category_manager" ],
    [ "City", "class_city.html", "class_city" ],
    [ "CityManager", "class_city_manager.html", "class_city_manager" ],
    [ "Comment", "class_comment.html", "class_comment" ],
    [ "CommentManager", "class_comment_manager.html", "class_comment_manager" ],
    [ "Contain", "class_contain.html", "class_contain" ],
    [ "ContentManager", "class_content_manager.html", "class_content_manager" ],
    [ "Error_controller", "class_error__controller.html", "class_error__controller" ],
    [ "Figurine", "class_figurine.html", "class_figurine" ],
    [ "FigurineManager", "class_figurine_manager.html", "class_figurine_manager" ],
    [ "Have", "class_have.html", "class_have" ],
    [ "HaveManager", "class_have_manager.html", "class_have_manager" ],
    [ "History", "class_history.html", "class_history" ],
    [ "HistoryManager", "class_history_manager.html", "class_history_manager" ],
    [ "Manager", "class_manager.html", "class_manager" ],
    [ "Order", "class_order.html", "class_order" ],
    [ "OrderManager", "class_order_manager.html", "class_order_manager" ],
    [ "Page_controller", "class_page__controller.html", "class_page__controller" ],
    [ "Photo", "class_photo.html", "class_photo" ],
    [ "PhotoManager", "class_photo_manager.html", "class_photo_manager" ],
    [ "Product", "class_product.html", "class_product" ],
    [ "Product_controller", "class_product__controller.html", "class_product__controller" ],
    [ "ProductManager", "class_product_manager.html", "class_product_manager" ],
    [ "Type", "class_type.html", "class_type" ],
    [ "TypesManager", "class_types_manager.html", "class_types_manager" ],
    [ "User_controller", "class_user__controller.html", "class_user__controller" ]
];